public class XSS_Mitigations_Challenge {
    
    public string sampleMergeField1 {
        get {
            return 'TEST DATA';
        }
        set;
    }
    
    public string sampleMergeField2 {
        get {
            return 'TEST DATA';
        }
        set;
    }
    
    public string sampleMergeField3 {
        get {
            return 'TEST DATA';
        }
        set;
    }
    
    public string sampleMergeField4 {
        get {
            return 'TEST DATA';
        }
        set;
    }
    
    public string sampleMergeField5 {
        get {
            return 'TEST DATA';
        }
        set;
    }
    
    public string sampleMergeField6 {
        get {
            return 'TEST DATA';
        }
        set;
    }
    
    public string sampleMergeField7 {
        get {
            return 'TEST DATA';
        }
        set;
    }
    
}